## Stößchen!

Mit Hilfe der folgenden Funktionen soll für die gegebene Eigenschaften einer Person, den von ihr konsumierten Getränken (Art & Anzahl) `drinks`  und der Zeitspanne (Anfang/Ende) `drinking_time` in der getrunken wurde die Blutalkoholkonzentration (in Promille) zum Ende der `drinking_time` berechnet.
Dafür werden Unterfunktionen verwendet.




Spezifikation:

- Ihre Funktion muß die Getränkearten "massn", "hoibe", "wein" und "schnaps" kennen. Für Bier nehmen Sie bitte oktoberfestmäßige 6% an, für Wein 11% und 0.2l pro Portion und für Schnaps 40% und 4cl pro Portion. 
- `drinks` kann als Liste (zB `list("massn" = 2, "schnaps" = 3)`) oder als Vektor übergeben werden (zB `c("wein" = 4, "hoibe" = 1)`). Ihre Funktion sollte beides akzeptieren.
- `height` wird in cm angeben, `weight` in kg.
- `drinking_time` bekommt einen Vektor von `POSIXct`-Zeitvariablen.

Lösen Sie die Aufgabe im Top-Down-Stil den Sie in der Vorlesung kennengelernt haben.  

Überprüfen Sie Ihre Funktion (mindestens) mit den Tests in `topdown-promille-tests.R`.

Die Aufrufe in `topdown-promille-errors.R`  sollten jeweils einigermassen aussagekräftige Fehlermeldungen produzieren. Ihre Funktionen sollten also gutes *input checking* machen, benutzen Sie dafür bitte die `assert_<BLA>()`-Funktionen aus dem Paket `checkmate`.


```{r}


tell_me_how_drunk(
      age = 39,
      sex = "male",
      height = 190,
      weight = 87,
      drinking_time = as.POSIXct(c("2016-10-03 17:15:00", "2016-10-03 22:55:00")),
      drinks = c("massn" = 3, "schnaps" = 4)
    )
```

